parameters:
  - name: displayName
    default: ''
    type: string
  - name: command
    default: ''
    type: string

jobs:
- job: ${{ parameters.displayName }}
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - template: ../steps/run-sonarcloudanalysis.yaml
    parameters:
      command: ${{ parameters.command }} ./gradlew clean sonarqube --stacktrace -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" -Psonar.login=8a5104e3e0960afa90a93fac3c56aae2fa4794d8 
  
