parameters:
  - name: displayName
    default: ''
    type: string
  - name: command
    default: ''
    type: string

jobs:
- job: ${{ parameters.displayName }}
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - template: ../steps/run-sonarcloudanalysis.yaml
    parameters:
      command: ${{ parameters.command }} 
