parameters:
  - name: displayName
    default: ''
    type: string
  
  - name: command
    default: ''
    type: string

jobs:
- job: ${{ parameters.displayName }}
  displayName: ${{ parameters.displayName }}

  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - template: ../steps/run-gradlew.yaml  
    parameters:
      command: ${{ parameters.command }}
      sonarAnalysis: true
      publishJUnitResults: false
