---
trigger:
  - none
pr: 
  - none
variables: 
  Sonarcloud_login: $(Psonar.login)
jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  
  parameters:
    displayName: 'Sonarcloudtest'
    command: sonarqube --stacktrace -$(Sonarcloud_login)


        

    

    

        



