---
trigger:
  - none
pr: 
  - none

jobs:
- template: pipeline/jobs/sonarqubetest.yaml
  parameters:
    displayName: 'Sonarcloudtest'
    command: 'sonarqube --stacktrace -$(Psonar.login)'


        

    

    

        



